apiVersion: v2
name: sipcapture
version: 0.4.0
description: HOMER/SIPCAPTURE stack
home: https://sipcapture.org
keywords:
  - voip 
  - monitoring 
  - pcap 
  - sip 
  - rtp
maintainers: 
  - name: Dave Horton
    email: daveh@drachtio.org
  - name: Lorenzo Mangani
    email: lorenzo.mangani@gmail.com
sources: 
  - https://github.com/sipcapture/helm-charts
  - https://github.com/jambonz/helm-charts

dependencies:
  - name: grafana
    version: 7.0.9
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.installOnCluster
  - name: postgresql
    version: 16.2.1
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: postgresql.installOnCluster