apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: heplify-server
  labels:
    app: heplify-server
{{ include "common.labels" . | indent 4 }}
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  serviceName: heplify-server
  replicas: 1
  selector:
    matchLabels:
      app: heplify-server
  template:
    metadata:
      labels:
        app: heplify-server
    spec:
      containers:
        - name: heplify-server
          image: {{ .Values.heplifyServer.image }}
          env:
          {{- range $key, $value := .Values.heplifyServer.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - containerPort: 9060
              protocol: UDP
            - containerPort: 9096
              protocol: TCP
          resources: {}