apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
  name: webapp-conf
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  bootstrapped: |
    bootstrapping