apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homer-webapp
{{ include "common.labels" . | indent 4 }}
  name: homer-webapp
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer-webapp
  template:
    metadata:
      labels:
        app: homer-webapp
    spec:
      containers:
        - name: homer-webapp
          image: {{ .Values.homer.image }}
          ports:
            - containerPort: 80
          resources: {}
          env:
          {{- range $key, $value := .Values.homer.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          volumeMounts:
            - mountPath: /homer-semaphore/.bootstrapped
              name: webapp-conf
              subPath: bootstrapped
      volumes:
      - name: webapp-conf
        configMap:
          name: webapp-conf
          items:
          - key: bootstrapped
            path: bootstrapped