---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ toYaml .Values.webApp.name }}
  name: {{ toYaml .Values.webApp.name }}
  namespace: {{ toYaml .Values.global.nameSpace }}
spec:
  ports:
    - name: webpage
      port: 80
      targetPort: 80
  type: NodePort
  selector:
    service: {{ toYaml .Values.webApp.name }}